# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.lifecycle.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nemoclaw-openshell.lifecycleServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nemoclaw-openshell.labels" . | nindent 4 }}
    app.kubernetes.io/component: lifecycle
  {{- with .Values.lifecycle.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
